version: "3"
services:
  api:
    command: bash pm2-runtime ./server/bin/www --node-args="--max_old_space_size=12288"
    environment: 
      NODE_ENV: "production"
    deploy:
      replicas: 1
      restart_policy:
        window: 90s
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 5s
    env_file:
      - api.env
    image: gcr.io/fundzero/red-ride_api:latest
    ports:
      - "3030:3030"
