version: '3'
services:
  postgresql:
    container_name: red-ride_db_test
    image: postgres:9.6.15
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: ""
    volumes:
      - ./data/postgresql-data-test:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
